### PR TITLE
fix(closes #546): Detect and fix corrupt cowBreedingPen state

### LINKED ISSUE #546: [Needs investigation] Trading a cow in the breeding pen causes corrupt game state
Wdn123 on Discord [discovered an issue](https://discord.com/channels/714539345050075176/822068921653788683/1368728669123776575) that required a save file modification to fix. Somehow their `cowBreedingPen` referenced a cow that was not in the inventory. This may have happened as a result of a trade while the cow was in the breeding pen, or possibly after all the cows ran away after not being fed.

### PR DESCRIPTION
**Pull request by jeremyckahn**
### What this PR does

This is a speculative mitigation for #546. If a corrupt `cowBreedingPen` state is detected when loading a save file, it is automatically fixed.

### How this change can be validated

This fixes an error state that has no known steps to reproduce, so all we can really do is verify that the tests pass and that there are no regressions.

- [ ] Verify that cow breeding pen state works as expected across days (i.e. cows are not unexpectedly removed from the breeding pen when ending the day)

### Questions or concerns about this change

This may not be strictly needed as #547 is intended to fix the root cause of #546. However, since the issue could not be reproduced, #547 cannot be verified to effectively solve the problem. This PR is more of a fallback solution to enable users to fix their game state by reloading the page.

### CODE REVIEW

**Comment by jeremyckahn** [comment]
> * **Minor Test Setup Redundancy**: In `src/utils/index.test.js`, within the `test.each` block for 'fixes corrupt cowBreedingPen if needed', the line `Object.assign(state, { cowBreedingPen, cowInventory })` (line 1091) is redundant. The `state` object is already modified by the direct assignments on lines 1089 and 1090. This is a very minor point and does not affect test correctness. (Not commented on directly due to review severity settings).

Whoops, this is fixed in https://github.com/jeremyckahn/farmhand/commit/b344a36b9c022db6a06b6da60b5504adc1a23a56.

**Review by lstebner — APPROVED** [review]

File: src/utils/index.js [hunk 1]
```diff
@@ -986,6 +986,40 @@ export const transformStateDataForImport = state => {
...
 
+  // NOTE: This is a mitigation for
+  // https://github.com/jeremyckahn/farmhand/issues/546. There's no expected
+  // scenario where a cow would be present in cowBreedingPen but not
+  // cowInventory, but at least one player's game somehow got into that state.
+  // This block detects such an invalid state and corrects it.
+  {
+    const { cowId1, cowId2 } = sanitizedState.cowBreedingPen
+
+    const cowPenIdMap = sanitizedState.cowInventory.reduce(
```
Comment (lstebner) [inline src/utils/index.js:997]: i know i already submitted approval but as soon as i did it occurred to me this might actually be a little simpler logic wise to use .some like 'const isCowMissing = [cow1id, cow2id].some(// check cow
pen for existence)' then your later if reads like 'if (isCowMissing) reset breeding pen'

sorry this comment is horribly formatted i'm on mobile. the way you have it works too i just wanted to offer a suggestion

Comment (jeremyckahn) [reply src/utils/index.js:997]: I like it! This is done in https://github.com/jeremyckahn/farmhand/commit/b6484cc7a8b08911da0e19d1fbe1ab125e267e34.
